<!DOCTYPE html>
<footer>
	<div class="bottom_flex">
		<nav>
			<ul>
				<li><a href="index.html"><img src="img/home.png" alt="">ホーム</a></li>
				<li><a href="menu.html"><img src="img/menu.png" alt="">メニュー</a></li>
				<li><a href="bonheur.html"><img src="img/bonheur.png" alt="">当店について</a></li>
				<li><a href="contact.html"><img src="img/contact.png" alt="">お問い合わせ</a></li>
			</ul>
		</nav>
		<div class="wrap">
			<img src="img/rogo.png" alt="">
			<div class="access">
				<p>〒010-1234<br>秋田県秋田市中通1-23</p>
				<p>TEL：<a href="tel:">123-456-7890</a>
				</p>
				<p>営業時間：9:00～18:00</p>
				<p>定休日：水曜日</p>
			</div>
		</div>
	</div>
	<p class="copy">Copyright © Bonheur All Rights Reserved.</p>
</footer>
</html>