<!DOCTYPE html>
<header>
	<a class="rogo_sp" href="index.html"><img src="img/rogo.png" alt="ロゴ"></a>
	<div class="btn-trigger" id="btn">
		<span></span>
		<span></span>
		<span></span>
	</div>
	<div id="navArea">
		<nav>
			<div class="inner">
				<ul>
					<li><a href="index.html"><img src="img/home.png" alt="ホーム"><ruby>HOME<rt>ホーム</rt></ruby></a></li>
					<li><a href="menu.html"><img src="img/menu.png" alt="メニュー"><ruby>MENU<rt>メニュー</rt></ruby></a></li>
					<li class="rogo"><a href="index.html"><img src="img/rogo.png" alt="ロゴ"></a></li>
					<li><a href="bonheur.html"><img src="img/bonheur.png" alt="当店について"><ruby>BONHEUR<rt>当店について</rt>
							</ruby></a>
					</li>
					<li><a href="contact.html"><img src="img/contact.png" alt="お問い合わせ"><ruby>CONTACT<rt>お問い合わせ</rt>
							</ruby></a>
					</li>
				</ul>
			</div>
		</nav>
		<a href=""><img class="sns_x" src="img/logo-black.png" alt="sns_x"></a>
		<a href=""><img class="sns_i" src="img/Instagram_Glyph_Black.png" alt="Instagram"></a>
	</div>
	<div id="mask"></div>
</header>
</html>